### ISSUE TITLE
Transition properties propagating in unexpected ways.

### ISSUE THREAD

**Issue by BrendanNeufeld** [Jam3/f1#5]
For example:
```javascript
'init', 'idle', {
        duration:0.75,
        preloader: { delay:3, duration:.75, ease: eases.elasticOut }
    }
```
the delay propagates upwards to the parent transition props
where as this does work:
```javascript
'init', 'idle', {
        duration:0.75,
        preloader: { position: {delay:3, duration:.75, ease: eases.elasticOut }},
    },
```
Essentially if you don't specify the property in the child it seems to propagate to either the parent or the other child.

**Comment by jmckinnell** [comment]
@MikkoH Have you looked at this? any feedback?

**Comment by MikkoH** [comment]
I've tested quickly and I didn't see anything abnormal will have to test again soonish. Or maybe @maxtherocket can look at this issue. Warning though the code that evaluates these is a bit daunting.

**Comment by maxtherocket** [comment]
Looking into this ....

**Comment by MikkoH** [comment]
I've hit this issue now. Started refactoring/simplifying some of the code that was causing this.
